### PR TITLE
WIP: German Translation

### PR DESCRIPTION
**Pull request by Toxantron**
I will translate the original README paragraph by paragraph. Feel free to join in if you speak German. 

I would recommend a Sqaush merge later to get rid of the temporary English used as a reference.

### CODE REVIEW

**Comment by m1key-d1ce** [comment]
Hey!
I am happy to help with the german translation.

**Comment by eamanu** [comment]
There are a lot of thins in English

**Comment by Toxantron** [comment]
@m1key-d1ce feel free to join. I copied the english version and started to translate it top down. Simply push to my branch and it will update this PR.

**Comment by eamanu** [comment]
@Toxantron @m1key-d1ce That is a good idea!

**Comment by elbatpord** [comment]
Hey, I'd like to take this over. However, I'm still new to this - I've already started translating the readme.md in a text file on my computer. How do I go on about posting my results when I'm ready?

**Comment by bueltge** [comment]
Because the PR is dead, the current status is here and needs your help https://github.com/bueltge/learn-regex/blob/master/translations/README-de.md

**Comment by JohnnyJayJay** [comment]
I finished this translation and made a PR to @bueltge 's fork. If you need me to open a separate PR for this repository, tell me

**Comment by bueltge** [comment]
So, thanks a lot to the helping hands of @JohnnyJayJay For now the translation is done and ready for the public readers. Thanks a lot for this great how-to. @ziishaned It would be fine if you merge them so that other people with background German language have the chance to read them. Best!

**Comment by ziishaned** [comment]
@bueltge can you please open a new PR with your fork because this PR still has lots of English that still needs to be translated

**Comment by bueltge** [comment]
Why not @ziishaned 
#212  has the content to get a solid translation. Best.

**Comment by ziishaned** [comment]
Thank you all for the contribution as we have a new PR #212 with complete German translation I will close this PR

**Pull request closed without merging**
